### ISSUE TITLE
lab3.2/winter.py

### ISSUE THREAD

**Issue by kolganovn** [python-practice-b02-927/Syrovatkin-Stepan#17]
1) Переименовать lab3.2 в lab3_2
2) Разбить программу на более мелкие блоки: например, сделать свою функцию для smoke,  building и cloud.
3) Форматирование кода: пробелы после запятых в аргументах функций, пробелы вместо табуляций, пустые строки должны быть совсем пустыми (без пробелов).

**Comment by ssyrovatkin** [comment]
Вроде сделал все, что написано
